### ISSUE TITLE
nrrd - Houdini 20.0.724 Py3.10

### ISSUE THREAD

**Issue by eldad3D** [TresSims/HoudiniFileInterpreters#2]
Hi,
Thanks for making this tool, great idea and I'd love to easily get .nrrd files to Houdini.

I followed your instructions and trying the sample file but getting this error. what should I do?

![image](https://github.com/user-attachments/assets/4039ee01-85f2-4994-864f-98ba5418eb3f)

Error 
Invalid source /obj/CT/Read_NRRD/python1.
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 62, in <module>
File "<stdin>", line 17, in read_nrrd
NameError: name 'nrrd' is not defined
). 

thanks again

**Comment by TresSims** [comment]
Hi! I just double checked on a fresh install of houdini 20.0, and it seemed to work so I don't think it's a bug with the code. 

That error usually means that you haven't successfully installed the `pynrrd` package to Houdini. The main cause of this is that you've installed the package to the python interpreter on your system. Houdini comes with it's own python interpreter that you need to install the package to in order to get this to work. 

If this is the case, the code should install the package automatically, and you should just need to save your scene and restart Houdini. 

If this doesn't work, let me know and we can troubleshoot some more.

**Comment by eldad3D** [comment]
First of all, you're the best, for getting back to me and trying to help.
thanks.

I'm trying to load but it doesn't work for me. When I tried earlier when I
uploaded the HDA it opened a new Houdini launch. but now it doesn't do that
and just gives me this error:
[image: image.png]

the ReadNRRD.py folder is in the user folder:
[image: image.png]
Should I do something there? I thought that's the environment folder you
meant in the readme file.

Thanks a lot

**Comment by TresSims** [comment]
Hi Eldad, 

It looks like your images haven't come through, could you try uploading them again? 

To clarify the installation instructions, the only file you should need to run the nrrd reader is the `otls/sop_ReadNRRD.hda`file, which you should copy somewhere on your Houdini Path, typically `$HOUDINI_USER_PREF_DIR/otls/sop_ReadNRRD.hda` where your `$HOUDINI_USER_PREF_DIR` is generally `~/houdinix.x` on linux or `C:\Users\%username%\Documents\houdiniX.X` on windows. 

For further troubleshooting, if you open up Houdini, and go to `Windows > Python Shell` and type `import nrrd` do you get an error or does the shell return?

**Comment by eldad3D** [comment]
i have the  sop_ReadNRRD.hda files.

Python shell came with errors:

Python 3.10.10 (main, Sep  7 2023, 14:15:07) [MSC v.1935 64 bit (AMD64)] on
win32
Houdini 20.0.625 hou module imported.
Type "help", "copyright", "credits" or "license" for more information.
>>>  import nrrd
  File "<console>", line 1
    import nrrd
IndentationError: unexpected indent
>>>

and I uploaded the images here.

**Comment by eldad3D** [comment]
the issue is resolved.
Thank you very much for creating the tool and your help!

**Comment by eldad3D** [comment]
the issue is resolved.
Thank you very much for creating the tool and your help!
